### PR TITLE
Fix python loading of blah.config

### PR DESCRIPTION
**Pull request by brianhlin**
- Use `ConfigParser` instead of janky shell commands that don't even work in the first place 
- Ensure that we get the absolute *status.py path, just to be safe

### CODE REVIEW

**Comment by djw8605** [comment]
I'm away from my laptop, but I agree with this change. Merge as you would like. 

-Derek

**Comment by brianhlin** [comment]
I've done some testing to ensure that the commands that are constructed based off of values in the blah.config are as expected.

**Comment by brianhlin** [comment]
FWIW, Clemson is successfully running with the latest changes

**Review by djw8605 — APPROVED** [review]
Looks good to me!

**Comment by djw8605** [comment]
Merge at your convenience

**Pull request merged**
