### PR TITLE
Allow users to set the SGE parallel environment policy

### PR DESCRIPTION
**Pull request by brianhlin**
https://jira.opensciencegrid.org/browse/SOFTWARE-2334

### CODE REVIEW

**Comment by djw8605** [comment]
I don't have a SGE cluster really to test this.  Have you tested these changes @brianhlin ?

**Comment by brianhlin** [comment]
Not against an SGE cluster but I have written a short test script where I verified that the proper string gets printed when sourcing the config template. We could have Doug Johnson test the exact change before we go ahead and merge this.

**Comment by djw8605** [comment]
Maybe scratch builds?

**Comment by brianhlin** [comment]
Doug was able to test this and he's satisfied: https://jira.opensciencegrid.org/browse/SOFTWARE-2334?focusedCommentId=338487&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-338487

**Pull request merged**
