### PR TITLE
New condor env format (SOFTWARE-3589)

### PR DESCRIPTION
**Pull request by brianhlin**
Resolves #73. @edquist Suchandra mentioned something about escaping spaces but glancing at his original commit, it wasn't immediately clear what spaces he was escaping. Please take a look.

### CODE REVIEW

**Comment by edquist** [comment]
@brianhlin has graciously pointed me to some condor [documentation](http://research.cs.wisc.edu/htcondor/manual/v8.6/condor_submit.html), which has helped clear up the story for me.

Suchandra's PR makes sense now.  He's trying to escape spaces within environment variable values with single-quotes (as required by the new format), since now each env var is whitespace-separated.

The only other detail I caught in the condor manual page is that single-quotes and double-quotes also need to be quoted by doubling them (`'` -> `''`, `"` -> `""`), in case these characters appear anywhere in the env var values.

**Comment by edquist** [comment]
Alright, I've added code to escape `'` and `"` characters in the environment.

I think this is ready to go, although I feel a bit funny about approving and merging my own changes, so @brianhlin I'll let you hit the merge button if you don't object to them.

**Review by edquist — APPROVED** [review]
Makes sense to me although these are my changes so someone else may want to give their rubber stamp also before merging.

**Comment by brianhlin** [comment]
And PR authors can't approve their own PRs :P. Looks pretty good to me. @JaimeFrey?

**Comment by edquist** [comment]
>And PR authors can't approve their own PRs :P. Looks pretty good to me.

Well, the rules are that the PR submitter can't approve said PR submitter's own PR, but the author of the commits can, if (as in this case) the two are separate users.  But the PR submitter (you) can merge it, I think, as I've already marked the PR as approved.  That's what I meant by rubber stamp :)

**Comment by edquist** [comment]
I've merged this, but if @JaimeFrey has any objections we can address them in a future PR.

**Pull request merged**
