### PR TITLE
Sw2199 sge colorado

### PR DESCRIPTION
**Pull request by brianhlin**
https://jira.opensciencegrid.org/browse/SOFTWARE-2199

### CODE REVIEW

**Comment by bbockelm** [comment]
How did all those commits sneak in?  Can you rebase?

**Comment by brianhlin** [comment]
Oops, bad merge. Should be fixed in both PR's.

**Comment by bbockelm** [comment]
I assume basically this is all the same stuff we do for the PBS scripts?

**Comment by brianhlin** [comment]
It's all the same stuff that we do for ALL the other blahp shell scripts. It's just that the SGE scripts were accidentally reverted a while back.

**Comment by brianhlin** [comment]
Specifically 708ae5d reverted some of the changes in 5303143

**Comment by bbockelm** [comment]
Sounds good - just wanted to make sure we're not going out on a limb.

**Pull request merged**
