### PR TITLE
Updated the changes from HTCondor ticket 5722 for SOFTWARE-2399

### PR DESCRIPTION
**Pull request by efajardo**
@djw8605,

I wonder if you could review this changes: 

I automatically tested them 👍 
http://vdt.cs.wisc.edu/tests/20160720-1749/results.html

And things look good. I basically merged Jaime's code from this ticket:

https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=5722

### CODE REVIEW

**Comment by djw8605** [comment]
We don't test slurm in our daily tests, do we?

**Comment by efajardo** [comment]
Nop I am waiting on Suchandra's secret sauce to test the slurm part. BUT we test PBS for regression

**Comment by efajardo** [comment]
WIth the help of Suchandra I was able to start a new COndor-CE with a Slurm backend. And I ran some jobs against them and they ran fine. So I wonder if you can now merge this @djw8605 ?

**Comment by bbockelm** [comment]
Can someone create a JIRA request (or point me at an existing one) for adding SLURM to the nightly tests?

**Comment by efajardo** [comment]
Ok created [SOFTWARE-2400](https://jira.opensciencegrid.org/browse/SOFTWARE-2400)

**Comment by djw8605** [comment]
The test that I would need to see to make sure it works with slurm:
1. Job is submitted through the blahp to a slurm cluster.
2. Job stays idle for at least 5 minutes.
3. Job runs for at least 5 minutes.
4. Job then completes.

The job needs to hit all of these points in order to fully test the `slurm_status.py` script.

Also, I would like to see the `condor_history` of a complete job.  It should show the memory usage, the correct exit code, and the cpu usage.

**Comment by efajardo** [comment]
@djw8605 ,

I performed all of those tests:

YOu can see it in the full sequence of condor_ce_q here:

```
[root@fermicloud391 condor-ce]# condor_ce_q
-- Schedd: fermicloud391.fnal.gov : <131.225.155.128:34809>
 ID      OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD               
  21.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  22.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  23.0   efajardo        7/21 13:57   0+00:00:21 R  0   0.0  myTestScript.sh 70
  24.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  25.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  26.0   efajardo        7/21 13:58   0+00:00:21 R  0   0.0  myTestScript.sh 70
  27.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70
  28.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70
  29.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70
  30.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70

10 jobs; 0 completed, 0 removed, 8 idle, 2 running, 0 held, 0 suspended

[root@fermicloud391 condor-ce]# condor_ce_q

-- Schedd: fermicloud391.fnal.gov : <131.225.155.128:34809>
 ID      OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD               
  21.0   efajardo        7/21 13:57   0+00:06:15 R  0   0.0  myTestScript.sh 70
  22.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  23.0   efajardo        7/21 13:57   0+00:11:16 C  0   3.4  myTestScript.sh 70
  24.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  25.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  27.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70
  28.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70
  29.0   efajardo        7/21 13:58   0+00:06:15 R  0   0.0  myTestScript.sh 70
  30.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70

9 jobs; 1 completed, 0 removed, 6 idle, 2 running, 0 held, 0 suspended
[root@fermicloud391 condor-ce]# condor_ce_q


-- Schedd: fermicloud391.fnal.gov : <131.225.155.128:34809>
 ID      OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD               
  21.0   efajardo        7/21 13:57   0+00:10:44 R  0   0.0  myTestScript.sh 70
  22.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  24.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  25.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  27.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70
  28.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70
  29.0   efajardo        7/21 13:58   0+00:10:44 R  0   0.0  myTestScript.sh 70
  30.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70

8 jobs; 0 completed, 0 removed, 6 idle, 2 running, 0 held, 0 suspended
[root@fermicloud391 condor-ce]# condor_ce_q


-- Schedd: fermicloud391.fnal.gov : <131.225.155.128:34809>
 ID      OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD               
  21.0   efajardo        7/21 13:57   0+00:10:46 R  0   0.0  myTestScript.sh 70
  22.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  24.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  25.0   efajardo        7/21 13:57   0+00:00:00 I  0   0.0  myTestScript.sh 70
  27.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70
  28.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70
  29.0   efajardo        7/21 13:58   0+00:10:46 R  0   0.0  myTestScript.sh 70
  30.0   efajardo        7/21 13:58   0+00:00:00 I  0   0.0  myTestScript.sh 70

```

And the history is here:

[condor_ce_history_slurm.txt](https://github.com/osg-bosco/BLAH/files/376975/condor_ce_history_slurm.txt)

**Comment by djw8605** [comment]
LGTM

**Comment by efajardo** [comment]
Thanks @djw8605 would you care of tagging a new release v1.18.21.bosco I seem to lack the permissions to do this

**Comment by djw8605** [comment]
Done: https://github.com/osg-bosco/BLAH/releases

**Pull request merged**
