### PR TITLE
Fix pbs_status.py to support older Slurm versions

### PR DESCRIPTION
**Pull request by winckler**
Fix pbs_status.py to be compatible with Slurm < 15.8. Also fix a close() call.

### CODE REVIEW

**Comment by djw8605** [comment]
Hi @winckler, I'm curious on the output of the `sacct` command when the noconvert flag is not given.  Especially the memory values.  For example, if it's 2G rather than 1.7GB, that's not quite as accurate as we would like.

**Comment by djw8605** [comment]
The only difference I could find between `--noconvert` and without is the frequency of the CPU changed from 4.29T to 4294898296K.  And we don't really care about that.

**Comment by winckler** [comment]
@djw8605 Sorry for the late reply, I was out of office.

I see that you merged the request. Thanks.
Do you still need more information?

**Comment by djw8605** [comment]
Hi @winckler, nope, I don't need any more information from you.  It looks good to us.

**Pull request merged**
